If you like this project and want to buy me an beer or support me in buying new hardware to implement the support feel free to send me a little tip.
Obviously this is optional and i have no intendation to commercialize anything :)

github: Lyr3x
