substitutions:
  sensor_name: roode_diag

external_components:
  - source: github://Lyr3x/Roode
    refresh: always

esphome:
  name: ${sensor_name}

esp32:
  board: wemos_d1_mini32

i2c:

vl53l1x:

roode:
  id: roode_platform

sensor:
  - platform: roode
    loop_time:
      name: ${sensor_name} loop time
    cpu_usage:
      name: ${sensor_name} cpu usage
    ram_free:
      name: ${sensor_name} free ram
    flash_free:
      name: ${sensor_name} free flash
