substitutions:
  devicename: roode8266
  friendly_name: $devicename
external_components:
  - source:
      type: git
      url: https://github.com/Lyr3x/Roode
      ref: master
esphome:
  name: $devicename
  platform: ESP8266
  board: d1_mini
  libraries:
    - pololu/VL53L1X@^1.3.0

<<: !include common/common.yaml

# Enable logging
logger:
  level: DEBUG

#status_led:
#  pin:
#    number: D0
#    inverted: True

web_server:
  port: 80
  auth:
    username: admin
    password: "1248"

i2c:
  sda: 4
  scl: 5

roode:
  id: roode_platform
  address: 0x29
  update_interval: 100ms
  calibration: true
  roi_height: 16
  roi_width: 6
  threshold_percentage: 80
  roi_calibration: false
  invert_direction: false
  restore_values: true

switch:
  - platform: restart
    name: $friendly_name Restart
binary_sensor:
  - platform: status
    name: $friendly_name Status
  - platform: roode
    presence_sensor:
      name: $friendly_name presence

sensor:
  - platform: roode
    id: hallway
    people_counter_sensor:
      id: peopleCounter
      name: $friendly_name people counter
    distance_sensor:
      name: $friendly_name distance
      filters:
        - delta: 100.0
    threshold_zone0:
      name: $friendly_name Zone 0
    threshold_zone1:
      name: $friendly_name Zone 1
    roi_height:
      name: $friendly_name ROI height
    roi_width:
      name: $friendly_name ROI width

  - platform: wifi_signal
    name: $friendly_name RSSI
    update_interval: 60s

  - platform: uptime
    name: Uptime Sensor
    id: uptime_sensor
    update_interval: 120s
    internal: true
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: uptime_human
            state: !lambda |-
              int seconds = round(id(uptime_sensor).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "d " : "") +
                (hours ? String(hours) + "h " : "") +
                (minutes ? String(minutes) + "m " : "") +
                (String(seconds) + "s")
              ).c_str();

text_sensor:
  - platform: roode
    version:
      name: $friendly_name version
  - platform: roode
    entry_exit_event:
      name: $friendly_name last direction

  - platform: template
    name: $friendly_name Uptime Human Readable
    id: uptime_human
    icon: mdi:clock-start
