; Only used to configure IDE
; Init after compiling with `esphome compile peopleCounterDev.yaml`

[platformio]
src_dir = components
include_dir = .esphome/build/roode32dev/src
lib_dir = .esphome/build/roode32dev/.piolibdeps/roode32dev

[env:roode]
framework = arduino
board = nodemcu-32s
platform = platformio/espressif32 @ 3.3.2
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:roode-c3]
framework = arduino
board = esp32-c3-devkitm-1
platform = platformio/espressif32 @ 6.6.0
build_unflags = -std=gnu++11
build_flags = -std=gnu++17
lib_ignore = AsyncTCP, ESPAsyncWebServer, RPAsyncTCP
