#!/usr/bin/env python3
"""Analyze passive scan session data to derive ROI and zone centers.

Usage:
    python roi_analysis.py <session_dir>

The session directory must contain a ``session.json`` file generated by
``session_recorder.py``. The analyzer computes the average photon counts per
SPAD across trials for each grid size and ranging mode, filters noisy cells and
estimates a region of interest (ROI). The ROI is then split into two clusters
representing entry and exit zones.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np


RANGING_BUDGET = {
    "short": 15,
    "medium": 20,
    "long": 33,
}


@dataclass
class ScanGroup:
    """Container for trials of the same grid/mode."""

    grid: int
    mode: str
    trials: List[np.ndarray]
    timestamps: List[datetime]
    idle_dists: List[np.ndarray]
    idle_mcps: List[np.ndarray] = field(default_factory=list)
    snr_trials: List[np.ndarray] = field(default_factory=list)

    def stats(self) -> Tuple[np.ndarray, np.ndarray]:
        arr = np.stack(self.trials, axis=0)
        return arr.mean(axis=0), arr.var(axis=0)


def mcps_floor(trials: Iterable[np.ndarray]) -> float:
    """Compute MCPS floor as max(5, 10th percentile of all readings)."""

    all_vals = np.concatenate([t for t in trials])
    return float(max(5.0, np.percentile(all_vals, 10)))


def cv_threshold(cv_values: np.ndarray, mad_factor: float = 0.5) -> float:
    """Return ``median(cv) + mad_factor*MAD(cv)`` threshold.

    Parameters
    ----------
    cv_values:
        Array of coefficient of variation values.
    mad_factor:
        Multiplier applied to the MAD. Typical range is 0.1–2.0.
    """

    med = np.nanmedian(cv_values)
    mad = np.nanmedian(np.abs(cv_values - med))
    return float(med + mad_factor * mad)


def apply_history(
    groups: Dict[Tuple[int, str], ScanGroup],
    session_dir: Path,
    half_life: float,
) -> Dict[Tuple[int, str], ScanGroup]:
    """Merge historical sessions weighted by exponential decay.

    ``half_life`` is specified in hours.
    """

    hist_file = session_dir / "history.json"
    if not hist_file.exists():
        return groups
    try:
        data = json.load(hist_file.open("r", encoding="utf-8"))
    except Exception:
        return groups
    now = datetime.now()
    for entry in data.get("sessions", []):
        try:
            ts = datetime.fromisoformat(entry["timestamp"])
        except Exception:
            continue
        age_h = (now - ts).total_seconds() / 3600.0
        weight = 0.5 ** (age_h / max(half_life, 1e-6))
        for key_str, trial_list in entry.get("groups", {}).items():
            grid_s, mode = key_str.split("|")
            grid = int(grid_s)
            groups.setdefault((grid, mode), ScanGroup(grid, mode, [], [], [], []))
            grp = groups[(grid, mode)]
            for arr in trial_list:
                grp.trials.append(np.array(arr) * weight)
    return groups

def load_session(session_dir: Path) -> Dict[Tuple[int, str], ScanGroup]:
    """Read ``session.json`` and group trials by grid/mode."""

    groups: Dict[Tuple[int, str], ScanGroup] = {}
    session_file = session_dir / "session.json"
    with session_file.open("r", encoding="utf-8") as fh:
        for line in fh:
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            if not isinstance(payload, dict):
                print(f"Skipping non-dict payload: {payload!r}")
                continue
            if payload.get("type") != "passive_scan":
                continue
            grid = int(payload["grid"])
            mode = payload["ranging"]
            mcps = np.array(payload["data"]["mcps"], dtype=float)
            ts = datetime.fromisoformat(payload.get("timestamp")) if "timestamp" in payload else datetime.now()
            groups.setdefault((grid, mode), ScanGroup(grid, mode, [], [], [], []))
            grp = groups[(grid, mode)]
            grp.trials.append(mcps)
            grp.timestamps.append(ts)
            idle_dist = np.array(payload["data"].get("idle_distance", []), dtype=float)
            if idle_dist.size:
                grp.idle_dists.append(idle_dist)
            idle_mcps = np.array(payload["data"].get("idle_mcps", []), dtype=float)
            if idle_mcps.size:
                grp.idle_mcps.append(idle_mcps)
            snr = np.array(payload["data"].get("snr", []), dtype=float)
            if snr.size:
                grp.snr_trials.append(snr)
    return groups


def stable_mask(
    mean: np.ndarray,
    var: np.ndarray,
    cv_limit: float | None = None,
    mad_factor: float = 0.5,
) -> np.ndarray:
    """Mask dim/unstable SPADs using median-based brightness and CV heuristics.

    Parameters
    ----------
    mean, var:
        Per-SPAD mean and variance arrays.
    cv_limit:
        Explicit CV threshold. Defaults to ``0.25`` when ``None``.  Values
        outside the ``0.15``–``0.35`` range raise :class:`ValueError`.
    mad_factor:
        Deprecated; retained for backward compatibility and ignored.
    """

    with np.errstate(divide="ignore", invalid="ignore"):
        cv = np.sqrt(var) / mean
    if cv_limit is None:
        cv_limit = 0.25
    if not 0.15 <= cv_limit <= 0.35:
        raise ValueError("cv_limit must be between 0.15 and 0.35")

    med = np.median(mean)
    mad = np.median(np.abs(mean - med))
    bright = mean >= med + 0.5 * mad
    mask = bright & (cv <= cv_limit)
    mask |= bright & np.isnan(cv)
    return mask


def weighted_centroid(weights: np.ndarray, mask: np.ndarray, grid: int) -> Tuple[float, float]:
    """Centroid of top fraction of SPADs by MCPS.

    The fraction ``k`` is derived from the number of unmasked SPADs ``N``
    using ``k = max(0.15, min(0.30, (64.0 / N) * 0.05))``. This heuristically
    scales the subset size while keeping it between 15% and 30% of available
    cells.
    """

    coords = np.indices((grid, grid)).reshape(2, -1).T.astype(float)
    N = int(mask.sum())
    if N == 0:
        return (grid - 1) / 2, (grid - 1) / 2
    w = weights[mask]
    pts = coords[mask]
    k = max(0.15, min(0.30, (64.0 / N) * 0.05))
    top_n = max(1, int(len(w) * k))
    idx = np.argsort(w)[-top_n:]
    w_top = w[idx]
    pts_top = pts[idx]
    cx = np.sum(w_top * (pts_top[:, 0] + 0.5)) / np.sum(w_top)
    cy = np.sum(w_top * (pts_top[:, 1] + 0.5)) / np.sum(w_top)
    return cx, cy


def mask_bounds(mask: np.ndarray, grid: int) -> Tuple[int, int, int, int]:
    coords = np.indices((grid, grid)).reshape(2, -1).T
    pts = coords[mask]
    min_x = int(pts[:, 0].min())
    max_x = int(pts[:, 0].max())
    min_y = int(pts[:, 1].min())
    max_y = int(pts[:, 1].max())
    return min_x, max_x, min_y, max_y


def thresholds_from_idle(
    idle_distances: Iterable[np.ndarray],
    mcps_max: float,
    min_idle_lo: float = 0.92,
    min_idle_hi: float = 0.96,
    idle_mcps: Iterable[np.ndarray] | None = None,
    snr_values: Iterable[np.ndarray] | None = None,
    target_snr: float = 7.0,
) -> Tuple[float, float]:
    """Return threshold percentages from idle distance and optional SNR data.

    The minimum threshold is estimated from the 95th percentile of idle
    distance samples and then clamped between ``min_idle_lo`` and
    ``min_idle_hi`` times the idle median distance.  If MCPS and SNR readings
    are provided the maximum threshold is derived from the lowest MCPS value
    whose corresponding SNR meets ``target_snr``.  Without SNR data the
    maximum defaults to ``0.80 * mcps_max``.  The result is finally clamped so
    the maximum stays at least ``10%`` above the minimum threshold.

    Parameters
    ----------
    idle_distances:
        Collection of idle distance readings.
    mcps_max:
        Maximum MCPS observed during the session.
    min_idle_lo:
        Lower clamp factor applied to the idle median when computing the minimum
        threshold.
    min_idle_hi:
        Upper clamp factor applied to the idle median when computing the minimum
        threshold.
    idle_mcps:
        Optional collection of idle MCPS readings for SNR evaluation.
    snr_values:
        Optional collection of SNR readings aligned with ``idle_mcps``.
    target_snr:
        Minimum acceptable SNR when deriving ``max_th``. Defaults to ``7``.
    """

    if not idle_distances:
        return 0.0, 0.85

    dist_arr = np.concatenate([s for s in idle_distances])
    idle_median = float(np.median(dist_arr))
    # Estimate the minimum threshold from the 95th percentile of idle distance
    # samples and clamp it to a safe range relative to the idle median.
    min_candidate = float(np.percentile(dist_arr, 95))
    min_candidate = float(
        np.clip(min_candidate, min_idle_lo * idle_median, min_idle_hi * idle_median)
    )
    min_th = min_candidate / idle_median

    max_th = min_th + 0.10
    if idle_mcps and snr_values:
        try:
            snr_arr = np.concatenate([s for s in snr_values])
            mcps_arr = np.concatenate([s for s in idle_mcps])
            mcps_median = float(np.median(mcps_arr))
            valid = snr_arr >= target_snr
            if np.any(valid):
                max_mcps = float(np.min(mcps_arr[valid]))
            else:
                max_mcps = 0.80 * mcps_max
            max_th = float(max(max_mcps / mcps_median, max_th))
        except Exception:
            max_th = float(max(0.80 * mcps_max, max_th))

    return min_th, max_th


def to_physical(x: float, y: float, grid: int) -> Tuple[float, float]:
    scale = 16 / grid
    return x * scale, y * scale


def center_index(x: float, y: float) -> int:
    return int(round(y) * 16 + round(x))


def kmeans(points: np.ndarray, weights: np.ndarray, iterations: int = 100) -> np.ndarray:
    """Simple weighted k-means for k=2."""
    probs = weights / weights.sum()
    idx = np.random.choice(len(points), size=2, replace=False, p=probs)
    centers = points[idx]
    for _ in range(iterations):
        dists = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)
        labels = dists.argmin(axis=1)
        new_centers = []
        for i in range(2):
            mask = labels == i
            if np.any(mask):
                w = weights[mask]
                new_centers.append(np.sum(points[mask] * w[:, None], axis=0) / w.sum())
            else:
                new_centers.append(centers[i])
        new_centers = np.array(new_centers)
        if np.allclose(new_centers, centers):
            break
        centers = new_centers
    return centers


def cluster_weight_ratio(points: np.ndarray, weights: np.ndarray, centers: np.ndarray) -> float:
    """Return ratio of total weights between the two clusters."""
    dists = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)
    labels = dists.argmin(axis=1)
    totals = [weights[labels == i].sum() for i in range(2)]
    if min(totals) <= 0:
        return float("inf")
    return float(max(totals) / min(totals))

def recommended_trials(var: np.ndarray, mean: np.ndarray) -> int:
    """Return 5 if average CV across trials >0.20 else 3."""

    with np.errstate(divide="ignore", invalid="ignore"):
        cv = np.sqrt(var) / mean
    avg_cv = np.nanmean(cv)
    return 5 if avg_cv > 0.20 else 3


def analyze(
    groups: Dict[Tuple[int, str], ScanGroup],
    mad_factor: float = 0.5,
    cv_limit: float | None = None,
    imbalance_ratio: float = 4.0,
    retry_axis: bool = True,
    retry_roi: bool = True,
    idle_min_lo: float = 0.92,
    idle_min_hi: float = 0.96,
    target_snr: float = 7.0,
) -> Dict[str, object]:
    """Apply adaptive heuristics to determine ROI, thresholds and zones.

    Parameters
    ----------
    groups:
        Mapping of grid/mode combinations to collected scan data.
    mad_factor:
        Placeholder for backward compatibility; unused.
    cv_limit:
        Coefficient-of-variation threshold. Defaults to ``0.25`` and must be
        within ``0.15``–``0.35``.
    imbalance_ratio, retry_axis, retry_roi:
        Existing tuning parameters for ROI selection.
    idle_min_lo, idle_min_hi:
        Clamp factors for the idle median when computing the minimum threshold.
    target_snr:
        Desired minimum SNR when determining the maximum threshold.
    """

    best_key = None
    best_var = float("inf")
    best_budget = float("inf")
    best_data = {}

    for key, grp in groups.items():
        mean, var = grp.stats()
        floor = mcps_floor(grp.trials)
        mask = stable_mask(mean, var, cv_limit=cv_limit, mad_factor=mad_factor)
        var_score = np.nanmean(var[mask])
        budget = RANGING_BUDGET.get(grp.mode, 999)
        if var_score < best_var or (np.isclose(var_score, best_var) and budget < best_budget):
            best_key = key
            best_var = var_score
            best_budget = budget
            best_data = {
                "group": grp,
                "mean": mean,
                "var": var,
                "mask": mask,
                "floor": floor,
            }

    if best_key is None:
        raise RuntimeError("No passive_scan data found")

    grp: ScanGroup = best_data["group"]
    mean = best_data["mean"]
    var = best_data["var"]
    mask = best_data["mask"]
    grid = grp.grid
    coords = np.indices((grid, grid)).reshape(2, -1).T.astype(float)
    roi_mask = mask
    axis_done = False
    roi_done = False
    centers = None
    while True:
        cx, cy = weighted_centroid(mean, roi_mask, grid)
        phys_x, phys_y = to_physical(cx, cy, grid)
        min_x, max_x, min_y, max_y = mask_bounds(roi_mask, grid)
        w_px = int(round((max_x - min_x + 1) * (16 / grid)))
        h_px = int(round((max_y - min_y + 1) * (16 / grid)))
        roi_center = center_index(phys_x, phys_y)

        stable_pts = coords[roi_mask]
        stable_weights = mean[roi_mask]
        phys_pts = np.array([to_physical(x + 0.5, y + 0.5, grid) for x, y in stable_pts])
        if len(stable_pts) < 2:
            centers = np.array([[phys_x, phys_y], [phys_x, phys_y]])
            break
        centers = kmeans(phys_pts, stable_weights)
        ratio = cluster_weight_ratio(phys_pts, stable_weights, centers)
        if ratio <= imbalance_ratio:
            break
        if not axis_done and retry_axis:
            alt = kmeans(phys_pts[:, ::-1], stable_weights)
            alt_ratio = cluster_weight_ratio(phys_pts[:, ::-1], stable_weights, alt)
            axis_done = True
            if alt_ratio <= imbalance_ratio:
                centers = alt[:, ::-1]
                break
        if not roi_done and retry_roi:
            roi_mask = mean >= best_data["floor"]
            roi_done = True
            continue
        break
    if centers[0, 1] <= centers[1, 1]:
        entry_c, exit_c = centers[0], centers[1]
    else:
        entry_c, exit_c = centers[1], centers[0]

    mcps_max = float(np.nanmax(mean))
    thr_min, thr_max = thresholds_from_idle(
        grp.idle_dists,
        mcps_max,
        min_idle_lo=idle_min_lo,
        min_idle_hi=idle_min_hi,
        idle_mcps=grp.idle_mcps,
        snr_values=grp.snr_trials,
        target_snr=target_snr,
    )
    trials_needed = recommended_trials(var, mean)

    return {
        "grid": grid,
        "mode": grp.mode,
        "roi": {"width": w_px, "height": h_px, "center": roi_center},
        "zones": {
            "entry": {"center": center_index(*entry_c)},
            "exit": {"center": center_index(*exit_c)},
        },
        "thresholds": {"min": thr_min, "max": thr_max},
        "recommended_trials": trials_needed,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("session_dir", type=Path, help="Path to session directory")
    parser.add_argument(
        "--half-life",
        type=float,
        default=336.0,
        help="Historical weighting half-life in hours (default: 14 days)",
    )
    parser.add_argument(
        "--mad-factor",
        type=float,
        default=None,
        help="Multiplier for MAD when deriving CV threshold (0.1-2.0)",
    )
    parser.add_argument(
        "--cv-mask",
        type=float,
        default=0.25,
        help="Explicit CV threshold (0.15-0.35). Default 0.25.",
    )
    parser.add_argument(
        "--imbalance-ratio",
        type=float,
        default=None,
        help="Weight ratio between clusters to trigger retries",
    )
    parser.add_argument(
        "--no-retry-axis",
        action="store_true",
        help="Disable retry with perpendicular axis on imbalance",
    )
    parser.add_argument(
        "--no-retry-roi",
        action="store_true",
        help="Disable retry with expanded ROI on imbalance",
    )
    parser.add_argument(
        "--idle-min-low",
        type=float,
        default=None,
        help="Lower clamp factor for idle median (default 0.92)",
    )
    parser.add_argument(
        "--idle-min-high",
        type=float,
        default=None,
        help="Upper clamp factor for idle median (default 0.96)",
    )
    parser.add_argument(
        "--target-snr",
        type=float,
        default=None,
        help="Minimum SNR required for max threshold (default 7)",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Optional JSON file with analysis parameters",
    )
    args = parser.parse_args()
    cfg = {}
    if args.config:
        try:
            cfg = json.load(args.config.open("r", encoding="utf-8"))
        except Exception:
            cfg = {}
    mad_factor = args.mad_factor if args.mad_factor is not None else cfg.get("mad_factor", 0.5)
    cv_mask = args.cv_mask if args.cv_mask is not None else cfg.get("cv_mask")
    imbalance_ratio = (
        args.imbalance_ratio if args.imbalance_ratio is not None else cfg.get("imbalance_ratio", 4.0)
    )
    retry_axis = cfg.get("retry_axis", True) and not args.no_retry_axis
    retry_roi = cfg.get("retry_roi", True) and not args.no_retry_roi
    idle_min_low = (
        args.idle_min_low if args.idle_min_low is not None else cfg.get("idle_min_low", 0.92)
    )
    idle_min_high = (
        args.idle_min_high if args.idle_min_high is not None else cfg.get("idle_min_high", 0.96)
    )
    target_snr = (
        args.target_snr if args.target_snr is not None else cfg.get("target_snr", 7.0)
    )
    groups = load_session(args.session_dir)
    groups = apply_history(groups, args.session_dir, args.half_life)
    result = analyze(
        groups,
        mad_factor=mad_factor,
        cv_limit=cv_mask,
        imbalance_ratio=imbalance_ratio,
        retry_axis=retry_axis,
        retry_roi=retry_roi,
        idle_min_lo=idle_min_low,
        idle_min_hi=idle_min_high,
        target_snr=target_snr,
    )
    out_file = args.session_dir / "roi_result.json"
    with out_file.open("w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2)
    hist_file = args.session_dir / "history.json"
    history = {"sessions": []}
    if hist_file.exists():
        try:
            history = json.load(hist_file.open("r", encoding="utf-8"))
        except Exception:
            history = {"sessions": []}
    history["sessions"].append(
        {
            "timestamp": datetime.now().isoformat(),
            "groups": {
                f"{g.grid}|{g.mode}": [t.tolist() for t in g.trials]
                for g in groups.values()
            },
        }
    )
    with hist_file.open("w", encoding="utf-8") as fh:
        json.dump(history, fh, indent=2)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
