#!/usr/bin/env python3
"""Analyze passive scan session data to derive ROI and zone centers.

Usage:
    python roi_analysis.py <session_dir>

The session directory must contain a ``session.json`` file generated by
``session_recorder.py``. The analyzer computes the average photon counts per
SPAD across trials for each grid size and ranging mode, filters noisy cells and
estimates a region of interest (ROI). The ROI is then split into two clusters
representing entry and exit zones.

Threshold derivation is controlled by ``min_factor_lo``, ``min_factor_hi`` and
``gap_factor`` values which may be supplied via a JSON config file.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

import numpy as np


RANGING_BUDGET = {
    "short": 15,
    "medium": 20,
    "long": 33,
}


@dataclass
class ScanGroup:
    """Container for trials of the same grid/mode."""

    grid: int
    mode: str
    trials: List[np.ndarray]
    timestamps: List[datetime]
    idle_trials: List[np.ndarray]

    def stats(self) -> Tuple[np.ndarray, np.ndarray]:
        arr = np.stack(self.trials, axis=0)
        return arr.mean(axis=0), arr.var(axis=0)


def mcps_floor(trials: Iterable[np.ndarray]) -> float:
    """Compute MCPS floor as max(5, 10th percentile of all readings)."""

    all_vals = np.concatenate([t for t in trials])
    return float(max(5.0, np.percentile(all_vals, 10)))


def cv_threshold(cv_values: np.ndarray, mad_factor: float = 0.5) -> float:
    """Return ``median(cv) + mad_factor*MAD(cv)`` threshold.

    Parameters
    ----------
    cv_values:
        Array of coefficient of variation values.
    mad_factor:
        Multiplier applied to the MAD. Typical range is 0.1–2.0.
    """

    med = np.nanmedian(cv_values)
    mad = np.nanmedian(np.abs(cv_values - med))
    return float(med + mad_factor * mad)


def apply_history(groups: Dict[Tuple[int, str], ScanGroup], session_dir: Path, half_life: float) -> Dict[Tuple[int, str], ScanGroup]:
    """Merge historical sessions weighted by exponential decay."""

    hist_file = session_dir / "history.json"
    if not hist_file.exists():
        return groups
    try:
        data = json.load(hist_file.open("r", encoding="utf-8"))
    except Exception:
        return groups
    now = datetime.now()
    for entry in data.get("sessions", []):
        try:
            ts = datetime.fromisoformat(entry["timestamp"])
        except Exception:
            continue
        age_h = (now - ts).total_seconds() / 3600.0
        weight = 0.5 ** (age_h / max(half_life, 1e-6))
        for key_str, trial_list in entry.get("groups", {}).items():
            grid_s, mode = key_str.split("|")
            grid = int(grid_s)
            groups.setdefault((grid, mode), ScanGroup(grid, mode, [], [], []))
            grp = groups[(grid, mode)]
            for arr in trial_list:
                grp.trials.append(np.array(arr) * weight)
    return groups

def load_session(session_dir: Path) -> Dict[Tuple[int, str], ScanGroup]:
    """Read ``session.json`` and group trials by grid/mode."""

    groups: Dict[Tuple[int, str], ScanGroup] = {}
    session_file = session_dir / "session.json"
    with session_file.open("r", encoding="utf-8") as fh:
        for line in fh:
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            if payload.get("type") != "passive_scan":
                continue
            grid = int(payload["grid"])
            mode = payload["ranging"]
            mcps = np.array(payload["data"]["mcps"], dtype=float)
            ts = datetime.fromisoformat(payload.get("timestamp")) if "timestamp" in payload else datetime.now()
            groups.setdefault((grid, mode), ScanGroup(grid, mode, [], [], []))
            grp = groups[(grid, mode)]
            grp.trials.append(mcps)
            grp.timestamps.append(ts)
            idle = np.array(payload["data"].get("idle_mcps", []), dtype=float)
            if idle.size:
                grp.idle_trials.append(idle)
    return groups


def stable_mask(
    mean: np.ndarray,
    var: np.ndarray,
    floor: float,
    cv_limit: float | None = None,
    mad_factor: float = 0.5,
) -> np.ndarray:
    """Mask dim/unstable SPADs using floor and CV heuristics.

    Parameters
    ----------
    mean, var:
        Per-SPAD mean and variance arrays.
    floor:
        Minimum MCPS value below which cells are masked.
    cv_limit:
        Explicit CV threshold. If ``None`` the threshold is determined using
        :func:`cv_threshold` with ``mad_factor``.
    mad_factor:
        Multiplier for MAD when deriving ``cv_limit`` if not supplied. Typical
        range is 0.1–2.0.
    """

    with np.errstate(divide="ignore", invalid="ignore"):
        cv = np.sqrt(var) / mean
    if cv_limit is None:
        cv_limit = cv_threshold(cv, mad_factor)
    mask = (mean >= floor) & (cv <= cv_limit)
    mask |= (mean >= floor) & np.isnan(cv)
    return mask


def weighted_centroid(weights: np.ndarray, mask: np.ndarray, grid: int, k: float = 0.3) -> Tuple[float, float]:
    """Centroid of top ``k`` fraction of SPADs by MCPS."""

    coords = np.indices((grid, grid)).reshape(2, -1).T.astype(float)
    w = weights[mask]
    pts = coords[mask]
    if len(w) == 0:
        return (grid - 1) / 2, (grid - 1) / 2
    k = float(np.clip(k, 0.05, 1.0))
    top_n = max(1, int(len(w) * k))
    idx = np.argsort(w)[-top_n:]
    w_top = w[idx]
    pts_top = pts[idx]
    cx = np.sum(w_top * (pts_top[:, 0] + 0.5)) / np.sum(w_top)
    cy = np.sum(w_top * (pts_top[:, 1] + 0.5)) / np.sum(w_top)
    return cx, cy


def mask_bounds(mask: np.ndarray, grid: int) -> Tuple[int, int, int, int]:
    coords = np.indices((grid, grid)).reshape(2, -1).T
    pts = coords[mask]
    min_x = int(pts[:, 0].min())
    max_x = int(pts[:, 0].max())
    min_y = int(pts[:, 1].min())
    max_y = int(pts[:, 1].max())
    return min_x, max_x, min_y, max_y


def snr(mean: np.ndarray, var: np.ndarray) -> np.ndarray:
    """Signal-to-noise ratio for each SPAD."""

    with np.errstate(divide="ignore", invalid="ignore"):
        return np.divide(mean, np.sqrt(var), out=np.zeros_like(mean), where=var > 0)


def thresholds_from_idle(
    idle_samples: Iterable[np.ndarray],
    snr_vals: np.ndarray,
    mcps_max: float,
    min_factor_lo: float = 0.92,
    min_factor_hi: float = 0.96,
    gap_factor: float = 0.10,
) -> Tuple[float, float]:
    """Determine min/max thresholds using idle median clamping and dynamic range heuristics.

    Parameters
    ----------
    idle_samples:
        Collection of idle MCPS readings.
    snr_vals:
        SNR values for the active trials.
    mcps_max:
        Maximum MCPS observed during active scanning.
    min_factor_lo, min_factor_hi:
        Bounds for clamping the minimum threshold relative to the idle median.
    gap_factor:
        Fraction of the active range added to ``min`` when deriving ``max``.
    """

    if not idle_samples:
        return 0.0, 0.85

    samples = np.concatenate([s for s in idle_samples])
    idle_med = float(np.median(samples))

    min_thr = float(np.percentile(samples, 5))
    max_thr = float(np.percentile(samples, 95))

    min_thr = float(np.clip(min_thr, idle_med * min_factor_lo, idle_med * min_factor_hi))
    max_thr = float(max(min_thr + gap_factor * (mcps_max - idle_med), max_thr))

    if np.nanmean(snr_vals) < 1.5:
        max_thr *= 0.9

    return min_thr, max_thr


def to_physical(x: float, y: float, grid: int) -> Tuple[float, float]:
    scale = 16 / grid
    return x * scale, y * scale


def center_index(x: float, y: float) -> int:
    return int(round(y) * 16 + round(x))


def kmeans(points: np.ndarray, weights: np.ndarray, iterations: int = 100) -> np.ndarray:
    """Simple weighted k-means for k=2."""
    probs = weights / weights.sum()
    idx = np.random.choice(len(points), size=2, replace=False, p=probs)
    centers = points[idx]
    for _ in range(iterations):
        dists = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)
        labels = dists.argmin(axis=1)
        new_centers = []
        for i in range(2):
            mask = labels == i
            if np.any(mask):
                w = weights[mask]
                new_centers.append(np.sum(points[mask] * w[:, None], axis=0) / w.sum())
            else:
                new_centers.append(centers[i])
        new_centers = np.array(new_centers)
        if np.allclose(new_centers, centers):
            break
        centers = new_centers
    return centers


def recommended_trials(var: np.ndarray, mean: np.ndarray) -> int:
    """Return 5 if average CV across trials >0.20 else 3."""

    with np.errstate(divide="ignore", invalid="ignore"):
        cv = np.sqrt(var) / mean
    avg_cv = np.nanmean(cv)
    return 5 if avg_cv > 0.20 else 3


def analyze(
    groups: Dict[Tuple[int, str], ScanGroup],
    mad_factor: float = 0.5,
    cv_limit: float | None = None,
    min_factor_lo: float = 0.92,
    min_factor_hi: float = 0.96,
    gap_factor: float = 0.10,
) -> Dict[str, object]:
    """Apply adaptive heuristics to determine ROI, thresholds and zones."""

    best_key = None
    best_var = float("inf")
    best_budget = float("inf")
    best_data = {}

    for key, grp in groups.items():
        mean, var = grp.stats()
        floor = mcps_floor(grp.trials)
        mask = stable_mask(mean, var, floor, cv_limit=cv_limit, mad_factor=mad_factor)
        snr_vals = snr(mean, var)
        var_score = np.nanmean(var[mask])
        budget = RANGING_BUDGET.get(grp.mode, 999)
        if var_score < best_var or (np.isclose(var_score, best_var) and budget < best_budget):
            best_key = key
            best_var = var_score
            best_budget = budget
            best_data = {
                "group": grp,
                "mean": mean,
                "var": var,
                "mask": mask,
                "snr": snr_vals,
                "floor": floor,
            }

    if best_key is None:
        raise RuntimeError("No passive_scan data found")

    grp: ScanGroup = best_data["group"]
    mean = best_data["mean"]
    var = best_data["var"]
    mask = best_data["mask"]
    snr_vals = best_data["snr"]
    grid = grp.grid

    cx, cy = weighted_centroid(mean, mask, grid)
    phys_x, phys_y = to_physical(cx, cy, grid)
    min_x, max_x, min_y, max_y = mask_bounds(mask, grid)
    w_px = int(round((max_x - min_x + 1) * (16 / grid)))
    h_px = int(round((max_y - min_y + 1) * (16 / grid)))
    roi_center = center_index(phys_x, phys_y)

    coords = np.indices((grid, grid)).reshape(2, -1).T.astype(float)
    stable_pts = coords[mask]
    stable_weights = mean[mask]
    phys_pts = np.array([to_physical(x + 0.5, y + 0.5, grid) for x, y in stable_pts])
    centers = kmeans(phys_pts, stable_weights)
    weights_clusters = []
    for c in centers:
        dists = ((phys_pts - c) ** 2).sum(axis=1)
        weights_clusters.append(stable_weights[dists.argmin()])
    if max(weights_clusters) / max(1.0, min(weights_clusters)) > 4:
        centers = kmeans(phys_pts, stable_weights, iterations=200)
    if centers[0, 1] <= centers[1, 1]:
        entry_c, exit_c = centers[0], centers[1]
    else:
        entry_c, exit_c = centers[1], centers[0]

    thr_min, thr_max = thresholds_from_idle(
        grp.idle_trials,
        snr_vals,
        float(np.nanmax(mean)),
        min_factor_lo=min_factor_lo,
        min_factor_hi=min_factor_hi,
        gap_factor=gap_factor,
    )
    trials_needed = recommended_trials(var, mean)

    return {
        "grid": grid,
        "mode": grp.mode,
        "roi": {"width": w_px, "height": h_px, "center": roi_center},
        "zones": {
            "entry": {"center": center_index(*entry_c)},
            "exit": {"center": center_index(*exit_c)},
        },
        "thresholds": {"min": thr_min, "max": thr_max},
        "recommended_trials": trials_needed,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("session_dir", type=Path, help="Path to session directory")
    parser.add_argument("--half-life", type=float, default=24.0, help="Historical weighting half-life in hours")
    parser.add_argument(
        "--mad-factor",
        type=float,
        default=None,
        help="Multiplier for MAD when deriving CV threshold (0.1-2.0)",
    )
    parser.add_argument(
        "--cv-mask",
        type=float,
        default=None,
        help="Explicit CV threshold (0-1); overrides MAD-based threshold",
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Optional JSON file with analysis parameters",
    )
    args = parser.parse_args()
    cfg = {}
    if args.config:
        try:
            cfg = json.load(args.config.open("r", encoding="utf-8"))
        except Exception:
            cfg = {}
    mad_factor = args.mad_factor if args.mad_factor is not None else cfg.get("mad_factor", 0.5)
    cv_mask = args.cv_mask if args.cv_mask is not None else cfg.get("cv_mask")
    min_factor_lo = cfg.get("min_factor_lo", 0.92)
    min_factor_hi = cfg.get("min_factor_hi", 0.96)
    gap_factor = cfg.get("gap_factor", 0.10)
    groups = load_session(args.session_dir)
    groups = apply_history(groups, args.session_dir, args.half_life)
    result = analyze(
        groups,
        mad_factor=mad_factor,
        cv_limit=cv_mask,
        min_factor_lo=min_factor_lo,
        min_factor_hi=min_factor_hi,
        gap_factor=gap_factor,
    )
    out_file = args.session_dir / "roi_result.json"
    with out_file.open("w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=2)
    hist_file = args.session_dir / "history.json"
    history = {"sessions": []}
    if hist_file.exists():
        try:
            history = json.load(hist_file.open("r", encoding="utf-8"))
        except Exception:
            history = {"sessions": []}
    history["sessions"].append(
        {
            "timestamp": datetime.now().isoformat(),
            "groups": {
                f"{g.grid}|{g.mode}": [t.tolist() for t in g.trials]
                for g in groups.values()
            },
        }
    )
    json.dump(history, hist_file.open("w", encoding="utf-8"), indent=2)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
