#!/usr/bin/env python3
"""Analyze passive scan session data to derive ROI and zone centers.

Usage:
    python roi_analysis.py <session_dir>

The session directory must contain a ``session.json`` file generated by
``session_recorder.py``. The analyzer computes the average photon counts per
SPAD across trials for each grid size and ranging mode, filters noisy cells and
estimates a region of interest (ROI). The ROI is then split into two clusters
representing entry and exit zones.
"""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np


@dataclass
class ScanGroup:
    grid: int
    mode: str
    trials: List[np.ndarray]

    def stats(self) -> Tuple[np.ndarray, np.ndarray]:
        arr = np.stack(self.trials, axis=0)
        return arr.mean(axis=0), arr.var(axis=0)

def load_session(session_dir: Path) -> Dict[Tuple[int, str], ScanGroup]:
    groups: Dict[Tuple[int, str], ScanGroup] = {}
    session_file = session_dir / "session.json"
    with session_file.open("r", encoding="utf-8") as fh:
        for line in fh:
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            if payload.get("type") != "passive_scan":
                continue
            grid = int(payload["grid"])
            mode = payload["ranging"]
            mcps = np.array(payload["data"]["mcps"], dtype=float)
            groups.setdefault((grid, mode), ScanGroup(grid, mode, []))
            groups[(grid, mode)].trials.append(mcps)
    return groups


def stable_mask(mean: np.ndarray, var: np.ndarray) -> np.ndarray:
    """Return mask of SPADs with MCPS>=10 and coefficient of variation<=0.1."""
    with np.errstate(divide="ignore", invalid="ignore"):
        cv = np.sqrt(var) / mean
    mask = (mean >= 10) & (cv <= 0.1)
    mask |= (mean >= 10) & np.isnan(cv)
    return mask


def weighted_centroid(weights: np.ndarray, mask: np.ndarray, grid: int) -> Tuple[float, float]:
    coords = np.indices((grid, grid)).reshape(2, -1).T.astype(float)
    pts = coords[mask]
    w = weights[mask]
    if w.sum() == 0:
        return (grid - 1) / 2, (grid - 1) / 2
    cx = np.sum(w * (pts[:, 0] + 0.5)) / np.sum(w)
    cy = np.sum(w * (pts[:, 1] + 0.5)) / np.sum(w)
    return cx, cy


def mask_bounds(mask: np.ndarray, grid: int) -> Tuple[int, int, int, int]:
    coords = np.indices((grid, grid)).reshape(2, -1).T
    pts = coords[mask]
    min_x = int(pts[:, 0].min())
    max_x = int(pts[:, 0].max())
    min_y = int(pts[:, 1].min())
    max_y = int(pts[:, 1].max())
    return min_x, max_x, min_y, max_y


def to_physical(x: float, y: float, grid: int) -> Tuple[float, float]:
    scale = 16 / grid
    return x * scale, y * scale


def center_index(x: float, y: float) -> int:
    return int(round(y) * 16 + round(x))


def kmeans(points: np.ndarray, weights: np.ndarray, iterations: int = 100) -> np.ndarray:
    """Simple weighted k-means for k=2."""
    probs = weights / weights.sum()
    idx = np.random.choice(len(points), size=2, replace=False, p=probs)
    centers = points[idx]
    for _ in range(iterations):
        dists = ((points[:, None, :] - centers[None, :, :]) ** 2).sum(axis=2)
        labels = dists.argmin(axis=1)
        new_centers = []
        for i in range(2):
            mask = labels == i
            if np.any(mask):
                w = weights[mask]
                new_centers.append(np.sum(points[mask] * w[:, None], axis=0) / w.sum())
            else:
                new_centers.append(centers[i])
        new_centers = np.array(new_centers)
        if np.allclose(new_centers, centers):
            break
        centers = new_centers
    return centers


def analyze(groups: Dict[Tuple[int, str], ScanGroup]) -> Dict[str, object]:
    best_key = None
    best_mask_count = -1
    best_total = -1.0
    best_data = {}

    for key, grp in groups.items():
        mean, var = grp.stats()
        mask = stable_mask(mean, var)
        count = mask.sum()
        total = mean[mask].sum()
        if count > best_mask_count or (count == best_mask_count and total > best_total):
            best_key = key
            best_mask_count = count
            best_total = total
            best_data = {
                "group": grp,
                "mean": mean,
                "var": var,
                "mask": mask,
            }

    if best_key is None:
        raise RuntimeError("No passive_scan data found")

    grp: ScanGroup = best_data["group"]
    mean = best_data["mean"]
    mask = best_data["mask"]
    grid = grp.grid
    cx, cy = weighted_centroid(mean, mask, grid)
    phys_x, phys_y = to_physical(cx, cy, grid)
    min_x, max_x, min_y, max_y = mask_bounds(mask, grid)
    w_px = int(round((max_x - min_x + 1) * (16 / grid)))
    h_px = int(round((max_y - min_y + 1) * (16 / grid)))
    roi_center = center_index(phys_x, phys_y)

    coords = np.indices((grid, grid)).reshape(2, -1).T.astype(float)
    stable_pts = coords[mask]
    stable_weights = mean[mask]
    phys_pts = np.array([to_physical(x + 0.5, y + 0.5, grid) for x, y in stable_pts])
    centers = kmeans(phys_pts, stable_weights)
    if centers[0, 1] <= centers[1, 1]:
        entry_c, exit_c = centers[0], centers[1]
    else:
        entry_c, exit_c = centers[1], centers[0]

    return {
        "grid": grid,
        "mode": grp.mode,
        "roi": {"width": w_px, "height": h_px, "center": roi_center},
        "zones": {
            "entry": {"center": center_index(*entry_c)},
            "exit": {"center": center_index(*exit_c)},
        },
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("session_dir", type=Path, help="Path to session directory")
    args = parser.parse_args()
    groups = load_session(args.session_dir)
    result = analyze(groups)
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
