name: Build ESP
on: push
jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'
      - name: Install ESPHome
        run: |
          python -m pip install --upgrade pip
          pip install -U esphome
      - name: Validate ESP32 Config
        run: esphome config peopleCounter32Dev.yaml
      - name: Build ESP32
        run: esphome compile peopleCounter32Dev.yaml
      
